"""Core dataclasses for lyrkl.

All models are plain Python dataclasses with no database logic.
They can be serialized to/from dicts for JSON export.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Optional


class VariantType(str, Enum):
    """Types of lyric prompt variants.

    PHONETIC: Phonetically similar but semantically different lyrics (APT).
    VERBATIM: Original lyrics unchanged (AVT upper-bound baseline).
    SEMANTIC: Paraphrased lyrics preserving meaning but changing sound.
    SHUFFLED: Original lyrics with line order shuffled (control).
    RANDOM: Lyrics from another song entirely (lower-bound control).
    STYLE_ONLY: No lyrics; uses only a style/caption description.
    """

    PHONETIC = "phonetic"
    VERBATIM = "verbatim"
    SEMANTIC = "semantic"
    SHUFFLED = "shuffled"
    RANDOM = "random"
    STYLE_ONLY = "style_only"


class VariantStatus(str, Enum):
    """Phi-based filtering status of a generated variant.

    ACCEPTED: Phi aggregate score meets the configured threshold.
    REJECTED: Phi score below threshold; kept in DB but not used.
    PENDING: Not yet scored.
    """

    ACCEPTED = "accepted"
    REJECTED = "rejected"
    PENDING = "pending"


class StyleSource(str, Enum):
    """Origin of a style description.

    LLM: Generated by a language model using world knowledge.
    CAPTIONER: Generated by an audio captioning model from an audio file.
    MANUAL: Manually authored.
    TEMPLATE: Produced by a heuristic template (fallback).
    """

    LLM = "llm"
    CAPTIONER = "captioner"
    MANUAL = "manual"
    TEMPLATE = "template"


@dataclass
class Song:
    """A song with its lyrics and optional audio link.

    Attributes:
        song_id: Unique slug, e.g. "eminem__lose_yourself".
        genius_id: Genius integer ID, used for direct lookups.
        title: Song title.
        artist: Primary artist name.
        genre: Genre label (user-supplied; Genius does not provide this).
        raw_lyrics: Raw text from Genius before cleaning.
        clean_lyrics: Lyrics after removing Genius artifacts and normalizing
            section markers to lowercase (e.g. [verse], [chorus]).
        fetched_at: UTC timestamp when lyrics were retrieved.
        audio_path: Optional filesystem path to a linked audio file.
        artist_gender: Optional gender label for the artist (e.g. "Female",
            "Male", "Nonbinary"). User-supplied; not available from Genius.
    """

    song_id: str
    title: str
    artist: str
    genre: str
    raw_lyrics: str = ""
    clean_lyrics: str = ""
    fetched_at: Optional[datetime] = None
    genius_id: Optional[int] = None
    audio_path: Optional[str] = None
    artist_gender: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict."""
        d = asdict(self)
        if self.fetched_at is not None:
            d["fetched_at"] = self.fetched_at.isoformat()
        return d

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Song":
        """Deserialize from a dict."""
        d = d.copy()
        if d.get("fetched_at"):
            d["fetched_at"] = datetime.fromisoformat(d["fetched_at"])
        return cls(**d)

    @property
    def has_lyrics(self) -> bool:
        """True if clean lyrics have been fetched."""
        return bool(self.clean_lyrics)


@dataclass
class StyleDescription:
    """A style/caption description for a song.

    Multiple rows may exist per song (different models, prompts, sources).
    The pipeline uses the most recently created row with source=llm by default.

    Attributes:
        desc_id: UUID string, primary key.
        song_id: Foreign key to Song.
        text: The style description text.
        source: How this description was produced (llm, captioner, etc.).
        model: Model name used to generate this description.
        prompt_hash: SHA-256 of the prompt used; used for idempotency.
        created_at: UTC timestamp.
    """

    desc_id: str
    song_id: str
    text: str
    source: StyleSource
    model: str
    prompt_hash: str
    created_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict."""
        d = asdict(self)
        d["source"] = self.source.value
        d["created_at"] = self.created_at.isoformat()
        return d


@dataclass
class LLMResponse:
    """Record of a single LLM API call and its raw output.

    Attributes:
        response_id: UUID string, primary key.
        song_id: Foreign key to Song.
        purpose: What this call was for, e.g. "apt" or "style".
        model: Full model identifier string.
        prompt_hash: SHA-256 of the exact prompt text sent.
        prompt_text: The full prompt text that was sent.
        response_text: The full raw text returned by the LLM.
        n_candidates: Number of candidate variations parsed from this response.
        raw_file_path: Absolute path to the `.txt` backup of the response.
        created_at: UTC timestamp.
    """

    response_id: str
    song_id: str
    purpose: str
    model: str
    prompt_hash: str
    prompt_text: str
    response_text: str
    n_candidates: int = 0
    raw_file_path: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict."""
        d = asdict(self)
        d["created_at"] = self.created_at.isoformat()
        return d


@dataclass
class PhiScores:
    """7-component phonetic similarity score (the Phi metric).

    Each component is in [0, 1]; higher means more phonetically similar.

    Attributes:
        phoneme: S_ph -- SequenceMatcher ratio on CMUdict phoneme sequences.
        rhyme: S_rh -- overlap of terminal phonemes (last stressed vowel + coda).
        syllable: S_sy -- syllable count similarity.
        stress: S_st -- stress pattern alignment.
        jaccard: S_jac -- Jaccard similarity over phoneme sets.
        cv_pattern: S_cv -- consonant-vowel pattern comparison.
        stressed_vowel: S_vow -- alignment of stressed vowel cores.
        aggregate: Phi_agg -- weighted mean of all components.
    """

    phoneme: float = 0.0
    rhyme: float = 0.0
    syllable: float = 0.0
    stress: float = 0.0
    jaccard: float = 0.0
    cv_pattern: float = 0.0
    stressed_vowel: float = 0.0
    aggregate: float = 0.0

    def to_dict(self) -> dict[str, float]:
        """Serialize to a plain float dict."""
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict[str, float]) -> "PhiScores":
        """Deserialize from a dict."""
        return cls(**d)

    @classmethod
    def from_json(cls, s: str) -> "PhiScores":
        """Deserialize from a JSON string."""
        return cls.from_dict(json.loads(s))

    def to_json(self) -> str:
        """Serialize to JSON string for DB storage."""
        return json.dumps(self.to_dict())


@dataclass
class Variation:
    """A generated lyric variant with Phi scoring and filter status.

    Attributes:
        var_id: SHA-256 of (song_id + prompt_hash + candidate_index).
            Content-addressed so re-generating identical text is idempotent.
        song_id: Foreign key to Song.
        variant_type: Which type of variation this is.
        lyrics: The variant lyric text.
        phi_scores: 7-component Phi scores (averaged across all lines).
        phi_aggregate: Phi_agg -- the scalar filter threshold metric.
        prompt_hash: Hash of the prompt template + model that produced this.
        llm_response_id: Foreign key to LLMResponse (null for VERBATIM/RANDOM).
        status: Whether this variant passed the Phi threshold filter.
        created_at: UTC timestamp.
        candidate_index: Index of this candidate within the LLM response (0-based).
    """

    var_id: str
    song_id: str
    variant_type: VariantType
    lyrics: str
    phi_scores: PhiScores
    phi_aggregate: float
    prompt_hash: str
    status: VariantStatus = VariantStatus.PENDING
    llm_response_id: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    candidate_index: int = 0

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict."""
        d = asdict(self)
        d["variant_type"] = self.variant_type.value
        d["status"] = self.status.value
        d["phi_scores"] = self.phi_scores.to_dict()
        d["created_at"] = self.created_at.isoformat()
        return d

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Variation":
        """Deserialize from a dict."""
        d = d.copy()
        d["variant_type"] = VariantType(d["variant_type"])
        d["status"] = VariantStatus(d["status"])
        d["phi_scores"] = PhiScores.from_dict(d["phi_scores"])
        if d.get("created_at"):
            d["created_at"] = datetime.fromisoformat(d["created_at"])
        return cls(**d)
